SECRET_KEY = "SECRET_KEY"
DATABASE = "DATABASE"


PASSWORD = "PASSWORD"

host = 'WEB_LINK'
MAIL_SERVER = "SMTP_SERTVER"
MAIL_PORT = "SERVER_PORT"
MAIL_USERNAME = "MAIL"
MAIL_PASSWORD = PASSWORD
MAIL_USE_TLS = False
MAIL_USE_SSL = True